name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7m-none-eabi

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install just
        uses: extractions/setup-just@v4

      - name: CI Sanity Check
        run: just ci_sanity
